spring.application.name=Climalert

# ----------------------------------------
# BASE DE DATOS (H2 en memoria)
# ----------------------------------------
spring.datasource.url=jdbc:h2:mem:climalertdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# ----------------------------------------
# CONFIGURACIÓN DE MAILS
# ----------------------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu_correo@gmail.com
spring.mail.password=tu_contrasena
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ----------------------------------------
# VARIABLES DE NUESTRO SISTEMA
# ----------------------------------------
weather.api.key=44bc0c3fd0a74c898b2172057262306
weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.location=CABA
