spring.application.name=Climalert

# ----------------------------------------
# BASE DE DATOS (H2 en memoria)
# ----------------------------------------
spring.datasource.url=jdbc:h2:mem:climalertdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# ----------------------------------------
# CONFIGURACIÓN DE MAILS
# ----------------------------------------
#Completar con la configuración del mail que se quiera usar (yo saque el mio antes de entregar)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= Completar con el mail
spring.mail.password= Completar con la contraseña
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ----------------------------------------
# VARIABLES DE NUESTRO SISTEMA
# ----------------------------------------
#Completar con la configuración de la api key gratuita que se quiera usar (yo saque la mia antes de entregar)
weather.api.key= Completar con la api key de WeatherApi
weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.location=CABA
